language: node_js
node_js:
  - 4
script: npm run $COMMAND
env:
  - COMMAND=test
  - COMMAND=integration MR_VERSION=16.0.5
  - COMMAND=integration MR_VERSION=latest
  - COMMAND=integration MR_VERSION="#master"
  - COMMAND=integration MONTAGE_VERSION=16.0.3
  - COMMAND=integration MONTAGE_VERSION=latest
  - COMMAND=integration MONTAGE_VERSION="#master"
jobs:
    include:
        - stage: deploy
        node_js: 4
        script: skip
        env:
        deploy:
            provider: npm
            email: "${NPM_EMAIL}"
            api_key: "${NPM_API_KEY}"
            on:
                tags: true
stages:
  - test
  - deploy
notifications:
  irc:
    channels:
      - "chat.freenode.net#montage"
    on_success: false
    template:
      - "%{author} broke the %{repository} tests on %{branch}: %{build_url}"
